name: Deploy to Aliyun OSS

on:
  push:
    branches:
      - main  # 触发部署的分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Aliyun OSS
        uses: JayMeDotDot/aliyun-OSS-deployer@v1.0.0
        with:
          access-key-id: ${{ secrets.ACCESSID }}  # 使用 GitHub Secrets
          access-key-secret: ${{ secrets.ACCESSSECRET }}  # 使用 GitHub Secrets
          bucket: photography-website
          endpoint: photography-website.oss-cn-hangzhou.aliyuncs.com
          # 其他可选参数根据需要添加，确保适当的缩进和格式
